### ISSUE TITLE
Is rabbitmq a required dependency?

### ISSUE THREAD

**Issue by barryz** [maticnetwork/node-ansible#18]
I have deployed Heimdall and Bor by the given scripts.  But I found the RabbitMQ service referenced by no one. 

So my question is: Is rabbitmq a required dependency?

**Comment by haliliceylan** [comment]
according to this tweet, i think not need https://twitter.com/_jdkanani/status/1411674637948186624

**Comment by haliliceylan** [comment]
you can use `ansible sentry -m apt --become -a "name=rabbitmq-server state=absent"`after install completed, it will delete rabbitmq-server from sentry nodes

**Comment by vcastellm** [comment]
@haliliceylan Your response is correct
